/*
 * ti816x_evm.h
 *
 * TI816X SoC EVM/SIM Config file.
 *
 * Copyright (C) 2009, Texas Instruments, Incorporated
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __CONFIG_TI816X_EVM_H
#define __CONFIG_TI816X_EVM_H

/*
 * Either of these defines come from top level config.h (autogenerated)
 *      #define CONFIG_TI816X_SIM
 *      ...
 */

/*
 * These features are unsupported
 */
#undef CONFIG_USE_IRQ
#undef CONFIG_NET_MULTI
#undef CONFIG_NET_RETRY_COUNT

/*
 * Size of malloc() pool
 */
#define CONFIG_SYS_MALLOC_LEN		(CONFIG_ENV_SIZE + (64 * 1024))
#define CONFIG_SYS_GBL_DATA_SIZE	128	/* size in bytes reserved for
						   initial data */

#ifdef CONFIG_TI816X_SIM
	#define CONFIG_SKIP_LOWLEVEL_INIT
	#define CONFIG_NOFLASH
	#define CONFIG_SKIP_RELOCATE_UBOOT
#endif

#define CONFIG_NOETH
#define CONFIG_L2_OFF			/* Avoid (OMAP3) secure mode stuff */

#ifndef CONFIG_NOR_BOOT
	#define CONFIG_NOFLASH		/* Revisit: For boot modes without NOR */
#endif

#ifdef CONFIG_NOR_BOOT
	#define CONFIG_SYS_FLASH_CFI
	#define CONFIG_MTD_DEVICE
	#define CONFIG_FLASH_CFI_DRIVER
	#define CONFIG_FLASH_CFI_MTD
	#define CONFIG_SYS_MAX_FLASH_SECT	512
	#define CONFIG_SYS_MAX_FLASH_BANKS	1
	#define CONFIG_ENV_IS_IN_FLASH		1
	#define CONFIG_SYS_FLASH_BASE		(0x00000000)
	#define CONFIG_SYS_MONITOR_BASE		CONFIG_SYS_FLASH_BASE
	#define NOR_SECT_SIZE				(128 * 1024)
	#define CONFIG_SYS_ENV_SECT_SIZE	(NOR_SECT_SIZE)
	#define CONFIG_ENV_OFFSET			(5 * NOR_SECT_SIZE)
	#define CONFIG_ENV_ADDR				(CONFIG_ENV_OFFSET)
#else
	#define CONFIG_SYS_MONITOR_BASE	    	TEXT_BASE
#endif

#define CONFIG_TI816X_EVM_DDR

#define CONFIG_CMDLINE_TAG        1	/* enable passing of ATAGs  */
#define CONFIG_SETUP_MEMORY_TAGS  1
#define CONFIG_INITRD_TAG	  1	/* Required for ramdisk support */

#define CONFIG_OMAP3_SPI
#define CONFIG_SPI_FLASH_STMICRO


/* U-Boot default commands */
#include <config_cmd_default.h>

#ifdef CONFIG_NOETH
#undef CONFIG_CMD_NET
#endif

/*
 * REVISIT: If we move this before including config_cmd_default.h, we won't need
 * to explicitly remove CONFIG_CMD_IMLS.
 */
#ifdef CONFIG_NOFLASH
#define CONFIG_SYS_NO_FLASH
#undef CONFIG_CMD_IMLS
#endif

#define CONFIG_BOOTDELAY        	3	/* set -1 for no autoboot */
#define CONFIG_VERSION_VARIABLE
#define CONFIG_BOOTARGS         "console=ttyS0,115200n8 root=/dev/SimBlkDev0 \
lpj=50000 mem=248M earlyprintk"

#define CONFIG_BOOTCOMMAND	"source 0x80000100; bootm 0x80700000"

#define	CONFIG_EXTRA_ENV_SETTINGS				        \
   "verify=no\0"

/*
 * Hardware drivers
 */


/**
 * Physical Memory Map
 */
#define CONFIG_NR_DRAM_BANKS	2		/* we have 2 banks of DRAM */
#define PHYS_DRAM_1		0x80000000	/* DRAM Bank #1 */
#define PHYS_DRAM_1_SIZE	0x40000000	/* 1 GB */
#define PHYS_DRAM_2		0xC0000000	/* DRAM Bank #2 */
#define PHYS_DRAM_2_SIZE	0x40000000	/* 1 GB */


/**
 * Platform/Board specific defs
 */
#define CONFIG_SYS_CLK_FREQ		12000000	/* TODO: Check! */
#define CONFIG_SYS_TIMERBASE		0x4802C000	/* TODO: Check! */

/*
 * NS16550 Configuration
 */
#define CONFIG_SYS_NS16550
#define CONFIG_SYS_NS16550_SERIAL
#define CONFIG_SYS_NS16550_REG_SIZE	(-4)
#define CONFIG_SYS_NS16550_CLK		(48000000)	/* TODO */
#define CONFIG_SYS_NS16550_COM1		0x48020000 	/* TODO */
					/*uart0 with h/w flow ctrl */

#define CONFIG_BAUDRATE			115200
#define CONFIG_SYS_BAUDRATE_TABLE	{ 110, 300, 600, 1200, 2400, \
4800, 9600, 14400, 19200, 28800, 38400, 56000, 57600, 115200 }

/*
 * select serial console configuration
 */
#define CONFIG_SERIAL1		1
#define CONFIG_CONS_INDEX	1

/**
 * Environment settings
 */
#ifdef CONFIG_NOFLASH
#define CONFIG_ENV_IS_NOWHERE
#endif

#define CONFIG_ENV_SIZE			0x8000

/*
 * Miscellaneous configurable options
 */
/* Undef to save memory */
#define CONFIG_SYS_LONGHELP
/* Monitor Command Prompt */
#define CONFIG_SYS_PROMPT		"=> "
/* Console I/O Buffer Size */
#define CONFIG_SYS_CBSIZE		256
/* Print Buffer Size */
#define CONFIG_SYS_PBSIZE		(CONFIG_SYS_CBSIZE \
					+ sizeof(CONFIG_SYS_PROMPT) + 16)
/* max number of command args */
#define CONFIG_SYS_MAXARGS		16
/* Boot Argument Buffer Size */
#define CONFIG_SYS_BARGSIZE		CONFIG_SYS_CBSIZE

/* memtest works on 8 MB in DRAM */
#define CONFIG_SYS_MEMTEST_START	(TEXT_BASE - (8 * 1024 * 1024) \
					- (1024 * 1024))
#define CONFIG_SYS_MEMTEST_END		(CONFIG_SYS_MEMTEST_START \
					+ (8 * 1024 * 1024))

#undef  CONFIG_SYS_CLKS_IN_HZ	/* everything, incl board info, in Hz */

#define CONFIG_SYS_LOAD_ADDR	0x80000100  /* Default load address */

#define CONFIG_SYS_HZ		1000        /* 1ms clock */

#endif	  /* ! __CONFIG_TI816X_EVM_H */
