/*
 * (C) Copyright 2006-2008
 * Texas Instruments, <www.ti.com>
 * Richard Woodruff <r-woodruff2@ti.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR /PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */
#ifndef _CLOCKS_TI816X_H_
#define _CLOCKS_TI816X_H_

/*
 * In TI816x the 27MHz crystal generates various root clks (main pll, audio pll, video pll and ddr pll)
 * From these root clks the SYSCLKs are generated by making use of dividers
 */

/* MAIN PLL */

#define MAIN_SYSCLK1_DIV	0x0	/* 800MHz GEM SS 	: CM_SYSCLK1_CLKSEL */
#define MAIN_SYSCLK2_DIV	0x0	/* 1GHz MONZA		: CM_SYSCLK2_CLKSEL */
#define MAIN_SYSCLK3_DIV	0x0	/* 600MHz IVA HDs	: CM_SYSCLK3_CLKSEL */
#define MAIN_SYSCLK4_DIV	0x0	/* 500MHz L3_FAST ETC	: CM_SYSCLK4_CLKSEL */
#define MAIN_SYSCLK7_DIV	0x0	/* 100MHZ VLYNQ		: CM_SYSCLK7_CLKSEL */
#define MAIN_SYSCLK23_DIV	0x0	/* 333MHZ SGX530	: CM_SYSCLK23_CLKSEL */
#define MAIN_SYSCLK24_DIV	0x0	/* 125MHZ GMII		: CM_SYSCLK24_CLKSEL */

/* THE DIVIDERS FOR SYSCLK 5,6 ARE FIXED AND CANT BE CHANGED */

/* DDR PLL */

#define DDR_SYSCLK8_DIV		0x0	/* 400MHZ DMM,EMIFS	: CM_SYSCLK8_CLKSEL */
#define DDR_SYSCLK9_DIV		0x0	/* 16MHz VTP		: CM_SYSCLK9_CLKSEL */
#define DDR_SYSCLK10_DIV	0x0	/* 48MHz SPI,I2C,UART	: CM_SYSCLK10_CLKSEL */
/* ROM CODE BUG: SYSCLK10_CLKSEL is taken as 1 i.e. DIV by2 giving 24Mhz and not 48Mhz.
 * The actual value has to be 0 i.e. DIV by 1 */

/* VIDEO PLL */

#define VIDEO_SYSCLK11_DIV	0x0	/* 218MHZ RF MOD	: CM_SYSCLK11_CLKSEL */
#define VIDEO_SYSCLK13_DIV	0x7	/* 165MHZ HD_VENC_D	: CM_SYSCLK13_CLKSEL */
#define VIDEO_SYSCLK15_DIV	0x3	/* 165MHZ HD_VENC_A	: CM_SYSCLK15_CLKSEL */
#define VIDEO_SYSCLK14_B3_DIV	0x2	/* STC0			: CM_VPB3_CLKSEL */
#define VIDEO_SYSCLK14_C1_DIV	0x3	/* STC0			: CM_VPC1_CLKSEL */
#define VIDEO_SYSCLK16_D1_DIV	0x7	/* STC1			: CM_VPD1_CLKSEL */
#define VIDEO_SYSCLK14_SRC	0x0	/* MUX FOR SYSCLK14 */

/* AUDIO PLL */

#define AUDIO_SYSCLK19_DIV	0x0	/* TPPSS		: CM_SYSCLK19_CLKSEL */
#define AUDIO_SYSCLK20_DIV	0x0	/* AUDIO CLK1		: CM_SYSCLK19_CLKSEL */
#define AUDIO_SYSCLK21_DIV	0x0	/* AUDIO CLK2		: CM_SYSCLK20_CLKSEL */
#define AUDIO_SYSCLK22_DIV	0x0	/* AUDIO CLK3		: CM_SYSCLK21_CLKSEL */
#define AUDIO_SYSCLK18_DIV	0x0	/* RTC			: CM_APA_CLKSEL */

/* Now the FAPLL multipler, divider, freq for the synthesizer for various PLLs needs to be given */

/* Main PLL */
#define MAIN_N			64
#define MAIN_P			0x1
#define MAIN_INTFREQ1		0x8
#define MAIN_FRACFREQ1		0x800000
#define MAIN_MDIV1		0x2
#define MAIN_INTFREQ2		0xE
#define MAIN_FRACFREQ2		0x0
#define MAIN_MDIV2		0x1
#define MAIN_INTFREQ3		0x8
#define MAIN_FRACFREQ3		0xAAAAB0
#define MAIN_MDIV3		0x3
#define MAIN_INTFREQ4		0x9
#define MAIN_FRACFREQ4		0x55554F
#define MAIN_MDIV4		0x3
#define MAIN_INTFREQ5		0x9
#define MAIN_FRACFREQ5		0x374BC6
#define MAIN_MDIV5		0xC

#define MAIN_MDIV6		0x48
#define MAIN_MDIV7		0x4

/* DDR PLL */
#define DDR_N			59
#define DDR_P			0x1

#define DDR_MDIV1		0x4

#define DDR_INTFREQ2		0x8
#define DDR_FRACFREQ2		0xD99999
#define DDR_MDIV2		0xF /* GEL uses 0x1E With this divider value, when ROM code runs we need to make this 0xF else console shows junk chars */
#define DDR_INTFREQ3		0x8
#define DDR_FRACFREQ3		0x0
#define DDR_MDIV3		0x4
#define DDR_INTFREQ4		0xE /* Expansion DDR clk */
#define DDR_FRACFREQ4		0x0
#define DDR_MDIV4		0x4
#define DDR_INTFREQ5		0xE /* Expansion DDR clk */
#define DDR_FRACFREQ5		0x0
#define DDR_MDIV5		0x4

/* Video PLL */
#define VIDEO_N			110
#define VIDEO_P			0x2
#define VIDEO_INTFREQ1		0xB
#define VIDEO_FRACFREQ1		0x0
#define VIDEO_MDIV1		0x5
#define VIDEO_INTFREQ2		0xA
#define VIDEO_FRACFREQ2		0x0
#define VIDEO_MDIV2		0x2
#define VIDEO_INTFREQ3		0xA
#define VIDEO_FRACFREQ3		0x0
#define VIDEO_MDIV3		0x2

/* Audio PLL */
#define AUDIO_N			64
#define AUDIO_P			0x19
#define AUDIO_INTFREQ2		0xE
#define AUDIO_FRACFREQ2		0x0
#define AUDIO_MDIV2		0x4
#define AUDIO_INTFREQ3		0x9
#define AUDIO_FRACFREQ3		0x0
#define AUDIO_MDIV3		0x5
#define AUDIO_INTFREQ4		0x9
#define AUDIO_FRACFREQ4		0xCBC148
#define AUDIO_MDIV4		0x14
#define AUDIO_INTFREQ5		0xD
#define AUDIO_FRACFREQ5		0x800000
#define AUDIO_MDIV5		0x14

#endif	/* endif _CLOCKS_TI816X_H_ */
